export class SubmitDetails
{   
    propId:number;
    title:String;
    propStatus:String;
    type:String;
    price:number;
    area:number;
    rooms:number;
    bathroom:number;
    address:String;
    postalcode:number;
    info:String;
    name:String;
    email:String;
    phone:number;
    parking:boolean=false;
    ac:boolean=false;
    balcony:boolean=false;
    pool:boolean=false;
    storage:boolean=false;
    gaspipe:boolean=false;
    alarm:boolean=false;
    pooja:boolean=false;
    laundry:boolean=false;
    city:String;
    state:String;
    buildingage:String;
    floor:String;
    noofparking:String;
    furnished:String;
    view:String;
    pd:any;
    location:String;
    image:any;
    propertyStat:String="activate";
constructor(title,propStatus,type,price,area,rooms,bathroom,address,postalcode,info,name,email,phone,parking,ac,image,
                balcony,pool,storage,gaspipe,alarm,pooja,laundry,city,state,buildingage,floor,noofparking,furnished,view,location,propertyStat)
        {
            this.name=name;
            this.email=email;
            this.propStatus=propStatus;
            this.type=type;
            this.rooms=rooms;
            this.bathroom=bathroom;
            this.title=title;
            this.price=price;
            this.area=area;
            this.address=address;
            this.postalcode=postalcode;
            this.phone=phone;
            this.info=info;
            this.parking=parking;
            this.ac=ac;
            this.balcony=balcony;
            this.pool=pool;
            this.storage=storage;
            this.gaspipe=gaspipe;
            this.alarm=alarm;
            this.pooja=pooja;
            this.laundry=laundry;
            this.city=city;
            this.state=state;
            this.buildingage=buildingage;
            this.floor=floor;
            this.noofparking=noofparking;
            this.furnished=furnished;
            this.view=view;
            this.location=location;
            this.image=image;
            this.propertyStat=propertyStat;
        }
    }